services:
  - type: web
    name: company-website-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && gunicorn config.wsgi --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,company-website-api.onrender.com,achyutdhital.com.np,www.achyutdhital.com.np
      - key: CSRF_TRUSTED_ORIGINS
        value: https://company-site-git-main-achyutdhital75-3174s-projects.vercel.app,https://company-website-api.onrender.com,https://www.achyutdhital.com.np,https://achyutdhital.com.np
      - key: CORS_ALLOWED_ORIGINS
        value: https://company-site-git-main-achyutdhital75-3174s-projects.vercel.app,https://www.achyutdhital.com.np,https://achyutdhital.com.np
