"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function NewTestimonial(){
  const [quote,setQuote]=useState(''); const [name,setName]=useState(''); const [company,setCompany]=useState(''); const [rating,setRating]=useState(5); const [error,setError]=useState(''); const router=useRouter();
  async function handleSubmit(e:React.FormEvent){ e.preventDefault(); setError(''); const token = localStorage.getItem('admin_token'); if(!token) return router.push('/admin/login'); const payload={quote,name,company,rating}; try{ const res = await fetch(`${process.env.NEXT_PUBLIC_API_BASE}/admin/testimonials/`, { method:'POST', headers:{ 'Content-Type':'application/json', Authorization:`Bearer ${token}` }, body: JSON.stringify(payload) }); if(!res.ok){ setError('Create failed'); return; } router.push('/admin/testimonials'); }catch(e){ setError('Create failed'); } }
  return (<div className="p-6 max-w-lg"><h2 className="text-xl font-bold mb-4">New Testimonial</h2><form onSubmit={handleSubmit} className="space-y-4"><div><label className="block text-sm font-medium">Quote</label><textarea value={quote} onChange={e=>setQuote(e.target.value)} className="mt-1 block w-full rounded border p-2"/></div><div><label className="block text-sm font-medium">Name</label><input value={name} onChange={e=>setName(e.target.value)} className="mt-1 block w-full rounded border p-2"/></div><div><label className="block text-sm font-medium">Company</label><input value={company} onChange={e=>setCompany(e.target.value)} className="mt-1 block w-full rounded border p-2"/></div><div><label className="block text-sm font-medium">Rating</label><input type="number" value={rating} onChange={e=>setRating(Number(e.target.value))} className="mt-1 block w-24 rounded border p-2"/></div>{error && <div className="text-red-600">{error}</div>}<div><button className="px-3 py-1 bg-sky-600 text-white rounded">Create</button></div></form></div>);
}
