# Generated by Django 6.0.5 on 2026-05-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('website_url', models.URLField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='EliteTech', max_length=200)),
                ('tagline', models.CharField(default='We build products that scale and convert.', max_length=255)),
                ('hero_title', models.CharField(default='We build digital products that win trust.', max_length=255)),
                ('hero_subtitle', models.TextField(default='From websites to platforms, we help ambitious businesses launch faster and look world-class.')),
                ('about_summary', models.TextField(default='EliteTech is a design-led engineering studio focused on building fast, premium digital experiences.')),
                ('email', models.EmailField(default='hello@elitetech.com', max_length=254)),
                ('phone', models.CharField(default='+977 9867512535', max_length=64)),
                ('whatsapp_number', models.CharField(default='9779867512535', max_length=32)),
                ('address', models.CharField(default='Kathmandu, Nepal', max_length=255)),
                ('hours', models.CharField(default='Sun-Fri, 9:00 AM - 6:00 PM', max_length=255)),
                ('years_experience', models.PositiveIntegerField(default=10)),
                ('projects_completed', models.PositiveIntegerField(default=120)),
                ('countries_served', models.PositiveIntegerField(default=5)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('ceo_name', models.CharField(default='Achu Dev', max_length=200)),
                ('ceo_role', models.CharField(default='Founder & CEO', max_length=200)),
                ('ceo_message', models.TextField(default='We build the kind of digital presence that makes businesses feel inevitable.')),
                ('google_maps_embed_url', models.URLField(blank=True, default='')),
            ],
        ),
    ]
